dev:
  log_level: "info"
  log_format: "colored"
  port: "3000"
  host: "127.0.0.1"
  live_data_poll_rate: "2000"

executors:
  sequential:
    in_process:

  multiprocessing:
    multiprocess:
      max_concurrent: 2

jobs:
  price_predictor_data_processing_test1:
    pipeline:
      pipeline_name: data_processing
      node_namespaces:
      - price_predictor
      tags:
      - test1
    executor: sequential

  price_predictor_data_science_test1:
    pipeline:
      pipeline_name: data_science
      node_namespaces:
      - price_predictor
      tags:
      - test1
    executor: sequential

  price_predictor_model_tuning_test1:
    pipeline:
      pipeline_name: model_tuning
      node_namespaces:
      - price_predictor
      tags:
      - test1
    executor: multiprocessing
