dev:
  log_level: "info"
  log_format: "colored"
  port: "3000"
  host: "127.0.0.1"
  live_data_poll_rate: "2000"

executors:
  sequential_executor:
    in_process:

  k8s_executor:
    k8s_job_executor:
      container_config:
        resources:
          requests:
          - cpu": 200m
          - memory: 32Mi

jobs:
  price_predictor_data_processing_test1:
    pipeline:
      pipeline_name: data_processing
      node_namespace: price_predictor
      tags:
      - test1
    executor: sequential_executor

  price_predictor_data_science_test1:
    pipeline:
      pipeline_name: data_science
      node_namespace: price_predictor
      tags:
      - test1
    executor: sequential_executor

  price_predictor_model_tuning_test1:
    pipeline:
      pipeline_name: model_tuning
      node_namespace: price_predictor
      tags:
      - test1
    executor: k8s_executor

