dev:
  log_level: "info"
  log_format: "colored"
  port: "3000"
  host: "127.0.0.1"
  live_data_poll_rate: "2000"

executors:
  in_process:
    in_process:

  multiprocess:
    multiprocess:
      max_concurrent: 2

jobs:
  reviews_predictor_base_data_processing:
    pipeline:
      pipeline_name: data_processing
      node_namespace: reviews_predictor
      tags:
      - base
    executor: in_process

  reviews_predictor_base_data_science:
    pipeline:
      pipeline_name: data_science
      node_namespace: reviews_predictor
      tags:
      - base
    executor: in_process

  reviews_predictor_base_model_tuning:
    pipeline:
      pipeline_name: model_tuning
      node_namespace: reviews_predictor
      tags:
      - base
    executor: multiprocess

  price_predictor_base_data_processing:
    pipeline:
      pipeline_name: data_processing
      node_namespace: price_predictor
      tags:
      - base
    executor: in_process

  price_predictor_base_data_science:
    pipeline:
      pipeline_name: data_science
      node_namespace: price_predictor
      tags:
      - base
    executor: in_process

  price_predictor_base_model_tuning:
    pipeline:
      pipeline_name: model_tuning
      node_namespace: price_predictor
      tags:
      - base
    executor: multiprocess

  price_predictor_data_processing_test1:
    pipeline:
      pipeline_name: data_processing
      node_namespace: price_predictor
      tags:
      - test1
    executor: in_process

  price_predictor_data_science_test1:
    pipeline:
      pipeline_name: data_science
      node_namespace: price_predictor
      tags:
      - test1
    executor: in_process

  price_predictor_model_tuning_test1:
    pipeline:
      pipeline_name: model_tuning
      node_namespace: price_predictor
      tags:
      - test1
    executor: in_process
