
loggers:
  file_logger:
    log_level: INFO
    formatters:
      simple:
        format: "[%(asctime)s] %(levelname)s - %(message)s"
    handlers:
      - class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: dagster_run_info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

  console_logger:
    log_level: INFO
    formatters:
      simple:
        format: "[%(asctime)s] %(levelname)s - %(message)s"
    handlers:
      - class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: simple

executors:
  sequential:
    in_process:

  multiprocessing:
    multiprocess:
      max_concurrent: 2

schedules:
  daily:
    cron_schedule: "30 2 * * *"

jobs:
  reviews_predictor_data_processing_base:
    pipeline:
      pipeline_name: data_processing
      node_namespaces:
      - reviews_predictor
      tags:
      - base
    loggers: ["console_logger", "file_logger"]
    executor: multiprocessing
    schedule: daily

  reviews_predictor_data_science_base:
    pipeline:
      pipeline_name: data_science
      node_namespaces:
      - reviews_predictor
      tags:
      - base
    loggers: ["console_logger", "file_logger"]
    executor: multiprocessing
    schedule: daily

  price_predictor_data_processing_base:
    pipeline:
      pipeline_name: data_processing
      node_namespaces:
      - price_predictor
      tags:
      - base
    loggers: ["console_logger", "file_logger"]
    executor: sequential
    schedule: daily

  price_predictor_data_science_base:
    pipeline:
      pipeline_name: data_science
      node_namespaces:
      - price_predictor
      tags:
      - base
    loggers: ["console_logger", "file_logger"]
    executor: sequential
    schedule: daily
