dev:
  log_level: "info"
  log_format: "colored"
  port: "3000"
  host: "127.0.0.1"
  live_data_poll_rate: "2000"

executors:
  sequential_executor:
    in_process:

  multiprocess_executor:
    multiprocess:
      max_concurrent: 2


schedules:
  daily_schedule:
    cron_schedule: "30 2 * * *"

jobs:
  reviews_predictor_data_processing_base:
    pipeline:
      pipeline_name: data_processing
      node_namespace: reviews_predictor
      tags:
      - base
    executor: sequential_executor
    schedule: daily_schedule

  reviews_predictor_data_science_base:
    pipeline:
      pipeline_name: data_science
      node_namespace: reviews_predictor
      tags:
      - base
    executor: multiprocess_executor
    schedule: daily_schedule

  price_predictor_data_processing_base:
    pipeline:
      pipeline_name: data_processing
      node_namespace: price_predictor
      tags:
      - base
    executor: sequential_executor
    schedule: daily_schedule

  price_predictor_data_science_base:
    pipeline:
      pipeline_name: data_science
      node_namespace: price_predictor
      tags:
      - base
    executor: sequential_executor
    schedule: daily_schedule
