name: Publish and share Kedro Viz

permissions:
  pages: write
  id-token: write

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-viz:
    name: Deploy Kedro Viz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          python-version: "3.13"

      - name: Sync uv
        run: uv sync --group viz

      - name: Deploy Kedro-Viz to GH Pages
        uses: kedro-org/publish-kedro-viz@v2
