name: Publish and share Kedro Viz

permissions:
  pages: write
  id-token: write

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-viz:
    name: Deploy Kedro Viz
    runs-on: ubuntu-latest
    env:
      KEDRO_ENV: local

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          python-version: "3.13"

      - name: Sync uv
        run: uv sync --group viz

      # This action does not support uv:
      # - name: Deploy Kedro-Viz to GH Pages
      #   uses: kedro-org/publish-kedro-viz@v2
      # Copying the action steps directly below

      - name: Create build directory
        run: |
          if !(uv run kedro viz build --include-hooks |& tee /dev/stderr | grep -i -q "Success!"); then
            exit 1
          fi
        shell: bash

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          path: "${{ github.workspace }}/build"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
